FROM hub.cr.parmincloud.ir/library/node:20.10-bookworm AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm set registry 'https://npm.parmincloud.ir'
RUN npm ci

COPY . .
RUN npm run build-storybook

FROM hub.cr.parmincloud.ir/library/nginx:bookworm
EXPOSE 80
COPY --from=build /app/storybook-static /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
