export const typeEnums = [
  { name: 'clinic.icon', label: 'لوگوی کلینیک' },
  { name: 'clinic.header', label: 'هدر کلینیک' },
  { name: 'clinic.gallery', label: 'عکس های کلینیک' },
  { name: 'user.profile', label: 'عکس پروفایل' },
  { name: 'user.import', label: 'مدارک کاربر' },
  { name: 'user.visit.opg', label: 'عکس opg ویزیت' },
  { name: 'user.visit.image', label: 'عکس ویزیت کاربر' },
  { name: 'user.avatar', label: 'تصویر پروفایل' },
  { name: 'user.opg', label: 'عکس OPG' },
  { name: 'user.cbct', label: 'عکس CBCT' },
  { name: 'category.icon', label: 'آیکون دسته بندی' },
  { name: 'serve.icon', label: 'آیکون خدمات' },
  { name: 'booking.files', label: 'مدارک نوبت' },
  { name: 'visit.files', label: 'مدارک ویزیت' },
  { name: 'credit-level', label: 'مدارک اعتبار سنجی' },
  { name: 'treatment-plan.financial', label: 'مدارک طرح درمان' },
  { name: 'user.cheques', label: 'چک‌ها' },
]
